from models.instituciones import Institucion
from models.estudiantes import Estudiante
from models.trabajos import Trabajo
from models.actas import Acta
from models.criterios import Criterio
from models.evaluacion_detalle import EvaluacionDetalle
from models.evaluaciones import Evaluacion
from models.evaluadores import Evaluador
from models.tipos_trabajo import TipoTrabajo